config/routes.rb
Rails.application.routes.draw do
root 'application#home'
resources :users
resources :companies do
  resources :reviews
end
resources :reviews, only: [:new, :create]

resources :users do
    resources :reviews, only: [:show ]
  end



get 'auth/facebook/callback', to: 'sessions#create'
get '/signin' => "sessions#new"
post '/signin' => "sessions#create"
# get '/signout' => "sessions#destroy"
# post '/signout'=> "sessions#destroy"
 delete '/logout' => 'sessions#delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :reviews
  has_many :users, :through=> :reviews
  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :company
  belongs_to :user
  accepts_nested_attributes_for :company
  validates :salary, presence: true
  validates :company, presence: true
  validates :women_exec_roles, presence: true
  validates :recommend, presence: true
  validates :job_rating, presence: true


  def company_attributes=(company_attribute)
      self.company = Company.find_or_create_by(company_attribute)
  end


  #if company exists in drop down, remove company size attribute, and attach existing company name to the user review
  #if company doesn't exist, include drop down for company size and create the company name and size along with user review

  # def company_name=(name)
  #    self.company = Company.find_or_create_by(name: name)
  # end
  #
  # def company_name
  #   self.company ? self.company.name : nil
  # end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :companies, :through=> :reviews
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true
  # before_create :set_anonymous_username
  # helper_method :set_anonymous_username
  has_secure_password

  def self.from_omniauth(auth)
      where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.username = auth.info.name
        user.email = auth.info.email
        user.password_digest = SecureRandom.hex
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
  end
end

#   def set_anonymous_username
#     @user.username = "anonymous#{User.last.id + 1}" if @user.username.nil?
#   end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in  

 def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end

 def logged_in
   current_user
 end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def new
    @company= Company.new
  end

  def create
    @company= Company.create(company_params)
      if @company.save
        redirect_to company_path(@company)
      end
    end

  def edit
  end

  def show
     @company = Company.find(params[:id])
  end

  def destroy
      @company= Company.find(params[:id])
        @company.delete
        redirect_to companies_path
      end

  private

  def company_params
    params.require(:company).permit(
      :name,
      :size)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @company = Company.find(params[:company_id])
  end

  def new
    if !params[:company_id]
      @review = Review.new
      @review.build_company
    else
      @review = Review.new
      @company = Company.find(params[:company_id])
    end
  end


  def create
      if !params[:company_id]
          @review = Review.create(reviews_params)
          @review.user_id = current_user.id
            if @review.save
              redirect_to company_reviews_path(@review.company), :notice => "Thank you for submitting your review"
            else
              redirect_to user_path(current_user), :notice => "boxes can't be blank"
            end
      else
          @company = Company.find(params[:company_id])
          @review = @company.reviews.create(reviews_params)
          @review.user_id = current_user.id
            if @review.save
               redirect_to company_reviews_path(@review.company), :notice => "Thank you for submitting your review"
            else
               redirect_to new_company_review_path, :notice => "boxes can't be blank"
            end
          end
        end

    def show
         @user = User.find(params[:user_id])
         @review = Review.find(params[:id])

         redirect_to :controller => 'reviews', :action => 'show'
     end

     def edit
            @company = Company.find(params[:company_id])
            @review = @company.comments.find(params[:id])
        end

    def update
            @company = Company.find(params[:company_id])
            @review = @company.reviews.find(params[:id])
            if @review.update(review_params)
                redirect_to @company
            else
                render 'companies/show'
            end
        end

    def destroy
            @company= Company.find(params[:company_id])
            @review = @company.reviews.find(params[:id])
            if @review.user_id == current_user.id
              @review.destroy
              redirect_to company_path
            end
          end


  private

  def reviews_params
    params.require(:review).permit(
      :user_id,
      :company_id,
      :content,
      :salary,
      :job_rating,
      :women_exec_roles,
      :promo_opps,
      :recommend,
      company_attributes: [:name]
      
      )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
        @auth = request.env["omniauth.auth"]
        if @auth
            @user = User.from_omniauth(request.env["omniauth.auth"])
            session[:user_id] = @user.id
            render user_path(@user), notice: "Successfully signed in"
           else
            @user = User.find_by(email: params[:email])
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id
                redirect_to  @user
            else
                render '/sessions/new', :notice => "Username/email/password incorrect or can't be blank"
            end
        end
    end

    def destroy
     session[:user_id] = nil
     session[:omniauth] = nil
     redirect_to root_url
   end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
        @user = User.new(user_params)
        @user.username = "anonymous#{User.last.id + 1}" if @user.username.nil?
        if @user.save
          session[:user_id] = @user.id
          redirect_to @user
        else
           render '/users/new'
        end

     end

  def show
     if logged_in
       @user = User.find_by(id: params[:id])
   else
       redirect_to '/'
     end
  end

  def edit
  end


    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to root_path
    end

private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :email, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
Welcome to UniquelyFem, an app that alleviates obstacles unique to women in the job search.
<br></br>
<br></br>
  <%= link_to('Log in with Facebook!', '/auth/facebook') %>
  <br></br>
 <%= link_to "Log In", signin_path %><br></br>
 <%= link_to "Sign Up", new_user_path %>

app/views/companies/_form.html.erb
<%= if current_user.admin %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@company.errors.count, "error") %>
        prohibited this post from being saved:
      </h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= form_for(@company) do |f| %>
      <p>
        <%= f.label :name, "Company Name:" %>
        <%= f.text_field :name %>
        <br></br>
        <%= f.label :size, "Company Size:" %>
        <%= f.number_field :size %>
        <br></br>
        <%= f.submit %></p>
  <% end %>

app/views/companies/edit.html.erb
<h2> Edit Company </h2>

<%= render 'form' %> 

app/views/companies/index.html.erb
<h2> List of All Companies </h2>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Company Reviews</strong></td>
      <td><strong> Company Details </strong></td>
      <td><strong>  Submit a Review </strong></td>

    </tr>
      <% @companies.each do |company|%>
      <tr>
        <td><%= company.name %></td>
        <% if company.reviews.exists? %>
        <td><%= button_to "See #{company.name} reviews", company_reviews_path(company), :method=> :get %></td>
        <% else %>
        <td> No Reviews Yet </td>
        <% end %>
        <td><%= button_to "Company Details", company_path(company), :method=> :get %></td>
        <td><%= button_to "Submit a review for this Company", new_company_review_path(company), :method=> :get%></td>
        <% if logged_in && current_user.admin %>
        <td><%= button_to "Delete Company", company_path(company), :method => :delete, :class => "delete", :confirm => "Are you sure?"%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br></br>
    <% if logged_in && current_user %>
        <p>
          <%= button_to "Back to Profile", user_path(current_user) %>
      <% elsif logged_in && current_user.admin %>
        <p>
          <%= button_to "Create a Company", new_company_path %>
        </p>
    <% end %>

app/views/companies/new.html.erb
<h2> Create a new company (only for admins) </h2>

<%= render 'form' %> 

app/views/companies/show.html.erb
<h2> Company Information </h2>
  <p> Name: <%= @company.name %>
  <p> Size: <%= @company.size %>

app/views/reviews/_form.html.erb
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@review.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for([@company, @review], {url: company_reviews_path, method: :post}) do |f| %>


  <%= f.label :company_name, "Company Name:" %>
      <%= f.text_field :company_name %>
      <br></br>
      <%= f.label :company_size, "Company Size:" %>
      <%= f.number_field :company_size %>
      <br></br>
      <%= f.label :salary, "Your Salary:" %>
      <%= f.number_field :salary %>
      <br></br>
      <%= f.label :women_exec_roles, "Are there women in leadership positions?" %>
      <%= f.check_box :women_exec_roles %>
      <br></br>
      <%= f.label :promo_opps, "Are there opportunities for promotion for women?" %>
      <%= f.check_box :promo_opps %>
      <br></br>
      <%= f.label :recommend, "Would you recommend this company to another a female friend?" %>
      <%= f.check_box :recommend %>
      <br></br>
      <%= f.label :job_rating, "What is your overall job satisfaction rating?" %>
      <%= f.number_field :job_rating %>
      <br></br>
      <%= f.label :content, "Any other details about the company (i.e. Maternity leave, remote work flexibility, company wide training etc.)" %>
      <br></br>
      <%= f.text_area :content %>
      <br></br>
 <%= f.submit %>
<% end %>

app/views/reviews/_form_with_co.html.erb
<!-- <% if @review.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@review.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> -->
<h2> Create a Review </h2>
<%= form_for(@review) do |f| %>
      <%= f.fields_for :company, @review.build_company do |company| %>
      <%= company.label :name, "Company Name:" %>
      <%= company.text_field :name, list: "companies_autocomplete" %>
        <datalist id= "companies_autocomplete">
            <% Company.all.each do |company| %>
            <option value="<%=company.name%>">
              <%end%>
        </datalist>
      <% end %>
      <br></br>
      <%= f.label :salary, "Your Salary:" %>
      <%= f.number_field :salary %>
      <br></br>
      <%= f.label :women_exec_roles, "Are there women in leadership positions?" %>
      <%= f.check_box :women_exec_roles %>
      <br></br>
      <%= f.label :promo_opps, "Are there opportunities for promotion for women?" %>
      <%= f.check_box :promo_opps %>
      <br></br>
      <%= f.label :recommend, "Would you recommend this company to another a female friend?" %>
      <%= f.check_box :recommend %>
      <br></br>
      <%= f.label :job_rating, "What is your overall job satisfaction rating?" %>
      <%= f.number_field :job_rating %>
      <br></br>
      <%= f.label :content, "Any other details about the company (i.e. Maternity leave, remote work flexibility, company wide training etc.)" %>
      <br></br>
      <%= f.text_area :content %>
      <br></br>
 <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h2>Edit your review </h2>

<%= render 'form' %> 

app/views/reviews/index.html.erb
<h2>All Reviews for <%=@company.name%> </h2>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

<ul>
  <% @company.reviews.each do |review| %>
  <p><%= review.user.username %> says:</p>
    <li><strong>salary:</strong> <%= review.salary %></li>
    <li><strong>Are there women in leadership positions?</strong> <%= review.women_exec_roles %></li>
    <li><strong>Are there opportunities for promotion for women?</strong> <%= review.promo_opps %></li>
    <li><strong>Would you recommend this company to a female fri</strong>end? <%= review.recommend %></li>
    <li><strong>What is your overall job satisfaction rating?(1-5) </strong><%= review.job_rating %></li>
    <li><strong>Any other details about the company
      (i.e. Maternity leave, remote work flexibility, company wide training etc.)</strong></li>
      <%=review.content%></p>
      <% if logged_in && review.user_id == current_user.id %>
        <p>
          <%= link_to "Edit Review", edit_company_review_path(@company, review) %>
          <%= button_to "Delete Review", company_review_path(@company, review), :method => :delete, :class => "delete", :confirm => "Are you sure ?"%>
          <%= button_to "See Company", company_path(@company), :method => :get %>
          <%= button_to "See all companies", companies_url, :method=> :get %>
            </p>
          <% end %>
        <% end %>
      </ul>



    <% if logged_in && @user == current_user %>
        <p>
          <%= link_to "My Account", user %>
          <%= link_to "My Reviews", review_path(current_user.review) %>
      <% end %>

app/views/reviews/new.html.erb
<% if !params[:company_id] %>
<%= render 'form_with_co' %>
<% else %>
<%= render 'form'%>
<% end %>

app/views/reviews/show.html.erb
<h2><%= current_user.username %>'s Reviews</h2>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :username, "Username:" %>
    <br>
    <%= f.text_field :username %>
    <br></br>

    <%= f.label :password, "Password:" %>
    <br>
    <%= f.password_field :password %>
    <br></br>

    <%= f.label :email, "Email:" %>
    <br>
    <%= f.text_field :email %>
    <br></br>

    <%= f.label :admin, "Check box if admin" %>
    <br>
    <%= f.check_box :admin %>
    <br></br>

    <%= f.submit "Sign Up" %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit your info: </h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if logged_in %>
  <h2> All Users </h2>
    <ul>
      <% @users.each do |user| %>
      <li><%=user.username %></li>
    <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= link_to('Sign Up with Facebook!', '/auth/facebook') %>
<br></br>
<%= render 'form' %>

app/views/users/show.html.erb
<% if current_user.admin %>
  <h3>ADMIN</h3> 
<% end %>
<h1><%= @user.username %>'s profile </h1>
<% if logged_in && @user == current_user %>
    <p>
    <%= link_to 'Edit', edit_user_path(@user) %>
    <%= form_tag user_path(@user.id), method: "delete" do %>
        <%= submit_tag "Delete #{@user.username}" %>
    <br></br>
    <%= link_to 'See all Companies', companies_path %>
    <br></br>
    <%= link_to 'Create a new Review', new_review_path %>
    <br></br>
    <%= link_to 'Log Out', signout_path %>
    <br></br>
    <% end %>
    </p>
<% elsif logged_in && current_user.admin %>
    <p>
    <%= link_to 'Edit', edit_user_path(@user) %>
    <%= form_tag user_path(@user.id), method: "delete" do %>
        <%= submit_tag "Delete #{@user.username}" %>
    <% end %>
    </p>
<% end %>